### ISSUE TITLE
Window viewport is broken with display scaling

### ISSUE THREAD

**Issue by klazoklazo** [AuroraViola/ChillyGB#1]
Using GNOME 46 in Ubuntu 24.04.1 LTS here, and trying to use the emulator with any scaling causes the game viewport to be too small and pushed off to the bottom left.

Here's an example of how this looks with 200% scaling:

![image](https://github.com/user-attachments/assets/da474ebf-ae92-4d01-9b0b-970f6ae8741d)

This applies to the rest of the UI as well, meaning that the menu bar as well as any windows within the main window are shrunken down the same:

![image](https://github.com/user-attachments/assets/fbd9010b-e45b-491e-a5ef-2adbd735499a)

Mouse actions still act as if the viewport is properly scaled to the full window's size, so despite the fact that the menu bar is pushed off to the bottom left, in order to access it you must still move your mouse around at the top left of the window.

This issue is not apparent with 100% scaling but seeing as I have a 4K monitor, this isn't a good workaround.

**Comment by AuroraViola** [comment]
What version are you using? Are you using the WASM port or the native Linux executable?
I develop the emulator on Fedora 41 with GNOME 47 and this issue doesn't seams to happen

**Comment by klazoklazo** [comment]
I'm utilizing the native executable obtained from the releases page here. Using 0.3.0.

![image](https://github.com/user-attachments/assets/0c7ff906-53b2-4f2b-af85-24c918a1902b)

**Comment by AuroraViola** [comment]
Hm, strange bug. I made a VM with Ubuntu 24.04.1 LTS and I don't get this issue.
![immagine](https://github.com/user-attachments/assets/39009ac7-0d87-49b4-8993-451c8abe8ba6)
Are you using Wayland or X11?

**Comment by klazoklazo** [comment]
I'm using Wayland. I tried using Visual Boy Advance - M and also ended up with the same bug, so this GitHub issue might also be related: https://github.com/visualboyadvance-m/visualboyadvance-m/issues/1364

**Comment by AuroraViola** [comment]
Does the issue still happens on X11?

**Comment by klazoklazo** [comment]
I checked and no, it seems the issue does not persist when using the Xorg option at login.

![Pasted image](https://github.com/user-attachments/assets/8224a8db-7eaa-4766-995a-defad8e8cf9e)

**Comment by scudo005** [comment]
Hi, can you test if this is an issue or not under xwayland? It's not perfect but it should work.

**Comment by klazoklazo** [comment]
![image](https://github.com/user-attachments/assets/1dec59c5-c1a8-4000-ace5-40b65a39cdfc)

I tried running the command `GDK_BACKEND=x11 ./ChillyGB` which creates the same issue albeit this time without any window decorations.

**Comment by AuroraViola** [comment]
It happens to be a Raylib building issue with the CI builds. If I use my OS Raylib libraries the issue doesn't show up

**Comment by scudo005** [comment]
I think this issue is caused by [poor Wayland support by Raylib](https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux#wayland). 

I don't know how good X11 support is under GNOME's compositor running under Wayland, but to me it looks like it's a Raylib issue. They know about it and they're trying to work around Wayland's limitations, so I'd guess (and hope) that this issue will fix itself in future Raylib releases. 

edit: I suggest running this application under X11 for now.

**Comment by klazoklazo** [comment]
Would you know how to run the application under X11 then? My attempt didn't seem to pan out too well in the sense that it did not fix the issue (I'm not even sure if it actually ended up running under X11).

**Comment by scudo005** [comment]
Sorry, I meant under an X11 session. It's not a good idea, but it works.

**Comment by AuroraViola** [comment]
I fixed the issue on the latest commit by disabling Wayland support in Raylib
